version: 2.1

orbs:
  terraform: circleci/terraform@3.2.1

jobs:
  validate:
    docker:
      - image: cimg/base:2023.03
    steps:
      - checkout
      - terraform/install:
          terraform_version: "1.5.7"
      - run:
          name: Copy test variables
          command: cp tests/terraform.tfvars .
      - terraform/fmt:
          check: true
      - terraform/init
      - terraform/validate
      - terraform/plan:
          path: .

workflows:
  version: 2
  terraform:
    jobs:
      - validate
